In [7]:
import numpy as np

# Membuat array NumPy
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Operasi Aritmatika
penjumlahan = array1 + array2
pengurangan = array1 - array2
perkalian = array1 * array2
pembagian = array1 / array2

# Statistik dasar
mean = np.mean(array1)
median = np.median(array1)
standar_deviasi = np.std(array1)

# menampilkan hasil array
print("Array 1:", array1)
print("Array 2:", array2)
print("Penjumlahan:", penjumlahan)
print("Pengurangan:", pengurangan)
print("Perkalian:", perkalian)
print("Pembagian:", pembagian)
print("Mean Array 1:", mean)
print("Median Array 1:", median)
print("Standar Deviasi Array 1:", standar_deviasi)


Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Penjumlahan: [6 6 6 6 6]
Pengurangan: [-4 -2  0  2  4]
Perkalian: [5 8 9 8 5]
Pembagian: [0.2 0.5 1.  2.  5. ]
Mean Array 1: 3.0
Median Array 1: 3.0
Standar Deviasi Array 1: 1.4142135623730951


In [5]:
#Operasi Aritmatika
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)   # Penjumlahan
print(x - y)   # Pengurangan
print(x * y)   # Perkalian
print(x / y)   # Pembagian
print(x ** 2)  # Pangkat


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [6]:
#Operasi Statistika
data = np.array([1, 2, 3, 4, 5])

print(np.mean(data))    # Rata-rata
print(np.median(data))  # Median
print(np.std(data))     # Standar deviasi
print(np.min(data))     # Nilai minimum
print(np.max(data))     # Nilai maksimum
print(np.sum(data))     # Jumlah total


3.0
3.0
1.4142135623730951
1
5
15


In [8]:
#Operasi Matriks
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perkalian matriks
print(np.dot(A, B))       # atau A @ B

# Transpos
print(A.T)

# Determinan
print(np.linalg.det(A))


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
-2.0000000000000004


In [10]:
#Fungsi Khusus
print(np.zeros((2, 3)))    # Array 2x3 berisi nol
print(np.ones((2, 2)))     # Array 2x2 berisi satu
print(np.eye(3))           # Matriks identitas 3x3
print(np.arange(0, 10, 2)) # Deret: 0, 2, 4, ..., <10
print(np.linspace(0, 1, 5))# 5 angka dari 0 sampai 1


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
